### ISSUE TITLE
Connect to VR server failed (301)

### ISSUE THREAD

**Issue by godbyk** [OSVR/SteamVR-OSVR#5]
When I run Steam VR, the control panel reports that it couldn't connect to the VR server (error 301) and therefore it couldn't find an HMD. (This appears to be a step backward from a couple versions where it would detect the HMD but complained that it wasn't receiving pose updates.)

I've attached some log files as well. In the `vrserver.txt` file, you can see where the OSVR driver reports having an available HMD. (The messages prefixed by `osvr`' are emitted by my driver.)

The `vrclient_vrmonitor.txt` log file shows the following two messages at the end:
```
    Timeout while waiting for message of type 101
    Invalid response to connect message. Connect failed
```
Per Joe of Valve Software:

> When an instance of vrclient (i.e. an app) connects to vrserver it sends message 100 (Connect) and expects message 101 (ConnectReponse) in response. In this case the connect is taking a long time to get back and the client will only wait 5 seconds. According to the vrserver log, though the whole startup process is taking less than a second so there’s something fishy going on.

![steamvr-control-panel-status-window](https://cloud.githubusercontent.com/assets/195036/8950019/4e63877e-3581-11e5-8c70-7fe0f3480a9f.png)

# vrserver.txt

    Wed Jul 08 02:59:18 2015 - ================================================================================================
    Wed Jul 08 02:59:18 2015 - ================================================================================================
    Wed Jul 08 02:59:18 2015 - VR server (v1435962534) starting up with config=C:\Program Files (x86)\Steam\config
    Wed Jul 08 02:59:18 2015 - Load Config from C:\Program Files (x86)\Steam\config\steamvr.cfg
    Wed Jul 08 02:59:18 2015 - lighthouse: Attached HID Devices:
    Wed Jul 08 02:59:18 2015 - lighthouse:     46D, C52B: s/n 㮷炿䂐0: Cordless Receiver
    Wed Jul 08 02:59:18 2015 - lighthouse:     46D, C52B: s/n Cordless Receiver: Cordless Receiver
    Wed Jul 08 02:59:18 2015 - lighthouse:     1532, 300: s/n \\?\hid#vid_1532&pid_0300&mi_00#7&221ec141&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}: Razer Hydra
    Wed Jul 08 02:59:18 2015 - lighthouse:     764, 501: s/n \\?\hid#vid_0764&pid_0501#6&3b240b79&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}:  CP 1350C
    Wed Jul 08 02:59:18 2015 - lighthouse:     46D, C221: s/n \\?\hid#vid_046d&pid_c221&mi_01&col01#8&31e94e87&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}: Gaming Keyboard
    Wed Jul 08 02:59:18 2015 - lighthouse:     46D, C221: s/n \\?\hid#vid_046d&pid_c221&mi_01&col02#8&31e94e87&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}: Gaming Keyboard
    Wed Jul 08 02:59:18 2015 - lighthouse:     46D, C222: s/n \\?\hid#vid_046d&pid_c222&col02#7&25bd4246&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}: G15 Keyboard
    Wed Jul 08 02:59:18 2015 - lighthouse:     46D, C52B: s/n \\?\hid#vid_046d&pid_c52b&mi_01&col02#8&7184af4&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030}: USB Receiver
    Wed Jul 08 02:59:18 2015 - lighthouse:     46D, C52B: s/n \\?\hid#vid_046d&pid_c52b&mi_01&col03#8&7184af4&0&0002#{4d1e55b2-f16f-11cf-88cb-001111000030}: USB Receiver
    Wed Jul 08 02:59:18 2015 - lighthouse:     572, 1410: s/n 00000000: RAZER USB AUDIO
    Wed Jul 08 02:59:18 2015 - lighthouse:     46D, C52B: s/n \\?\hid#vid_046d&pid_c52b&mi_01&col04#8&7184af4&0&0003#{4d1e55b2-f16f-11cf-88cb-001111000030}: USB Receiver
    Wed Jul 08 02:59:18 2015 - Driver lighthouse has no HMDs. Skipping
    Wed Jul 08 02:59:18 2015 - oculus: Found 0 Oculus devices
    Wed Jul 08 02:59:18 2015 - Driver oculus has no HMDs. Skipping
    Wed Jul 08 02:59:18 2015 - osvr: ServerDriver_OSVR::Init() called.
    Wed Jul 08 02:59:18 2015 - osvr: ServerDriver_OSVR::GetTrackedDeviceCount(): Detected 1 tracked devices.
    Wed Jul 08 02:59:18 2015 - osvr: ServerDriver_OSVR::GetTrackedDeviceCount(): Detected 1 tracked devices.
    Wed Jul 08 02:59:18 2015 - osvr: ServerDriver_OSVR::GetTrackedDeviceDriver(): Returning tracked device 0.
    Wed Jul 08 02:59:18 2015 - osvr: ServerDriver_OSVR::GetTrackedDeviceCount(): Detected 1 tracked devices.
    Wed Jul 08 02:59:18 2015 - osvr: ServerDriver_OSVR::GetTrackedDeviceDriver(): Returning tracked device 0.
    Wed Jul 08 02:59:18 2015 - osvr: ServerDriver_OSVR::GetTrackedDeviceCount(): Detected 1 tracked devices.
    Wed Jul 08 02:59:18 2015 - Active HMD set to osvr.OSVR HMD

# vrmonitor.txt

    Wed Jul 08 02:59:17 2015 - ================================================================================================
    Wed Jul 08 02:59:17 2015 - ================================================================================================
    Wed Jul 08 02:59:17 2015 - vrmonitor starting up with config=C:\Program Files (x86)\Steam\config
    Wed Jul 08 02:59:17 2015 - Runtime: C:\Program Files (x86)\Steam\steamapps\common\SteamVR
    Wed Jul 08 02:59:17 2015 - Load Config from C:\Program Files (x86)\Steam\config\steamvr.cfg
    Wed Jul 08 02:59:17 2015 - Tools Path: C:\Program Files (x86)\Steam\steamapps\common\SteamVR\tools exists.
    Wed Jul 08 02:59:17 2015 - Demo Path: C:\Program Files (x86)\Steam\steamapps\common\SteamVR\demo exists.
    Wed Jul 08 02:59:23 2015 - Unable to get shared openGL context when initializing overlay bridgeWed Jul 08 02:59:43 2015 - Open URL vrmonitor://open/statusreport
    Wed Jul 08 03:01:42 2015 - Open URL vrmonitor://open/statusreport

# vrclient_vrmonitor.txt

    Wed Jul 08 02:59:17 2015 - vrclient startup with PID=6532, config=C:\Program Files (x86)\Steam\config
    Wed Jul 08 02:59:17 2015 - Load Config from C:\Program Files (x86)\Steam\config\steamvr.cfg
    Wed Jul 08 02:59:17 2015 - Starting vrserver process: C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win32\vrserver.exe
    Wed Jul 08 02:59:23 2015 - Timeout while waiting for message of type 101 
    Wed Jul 08 02:59:23 2015 - Invalid response to connect message. Connect failed

**Comment by antcodd** [comment]
Found the reason for this. Infinite loop in vrserver due to a typo in a nested loop:

`vr::HmdMatrix34_t OSVRTrackedDevice::GetHeadFromEyePose(vr::Hmd_Eye eye)` (osvr_tracked_device.h:388)
```C++
vr::HmdMatrix34_t OSVRTrackedDevice::GetHeadFromEyePose(vr::Hmd_Eye eye)
{
    vr::HmdMatrix34_t matrix;
    // TODO

    // Return an identity matrix for now
    for (int i = 0; i < 3; ++i) {
        for (int j = 0; j < 4; ++i) {
            matrix.m[i][j] = (i == j ? 1.f : 0.f);
        }
    }

    return matrix;
}
```

Now connects but get no head pose. Not sure if this function needs to be implemented properly first?
Note: I have no headset and haven't really explored the code base. My intention is to try and get SteamVR connected to Cardboard.

PS: Why does this header file have so much implementation in it?

**Comment by rpavlik** [comment]
Thanks for noticing this! I've pushed changes that resolve that loop issue and all similar ones (by using an object/expression-based method of converting math types, as well as the Eigen math library).

**Comment by d235j** [comment]
I have not experienced this issue; can someone else test and close if fixed?

**Comment by pavlo1031** [comment]
@d235j :
so you can play steamVR game using osvr hmd? these 2 interact normally for you?

**Comment by d235j** [comment]
@pavlo1031: I was able to, at least up until a recent build which seems to have changed the SteamVR driver API (without updating the "OpenVR" headers), so I'm stuck until this is resolved. Try previous versions in the betas tab for SteamVR, but be warned — the steamvr server may not start automatically if you're on Mac OS or Linux.

**Comment by pavlo1031** [comment]
i'm using the driver "Windows alpha binaries:  Download Windows Alpha", still trying and the issue is still there, which has the only directory "drivers" in it.

do i have to rebuild this project for my own driver on my computer?

**Comment by d235j** [comment]
@pavlo1031: what issue are you experiencing exactly? You shouldn't have to rebuild it.
Are you following the instructions at https://github.com/OSVR/SteamVR-OSVR#binary-usage-instructions?

**Comment by pavlo1031** [comment]
um..actually my english is not really good, cannot figure out some words and phrases. i'm trying to understand these 3 paragraphs:

=  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 
If you accepted defaults, Steam's nested SteamVR directory is installed in "%ProgramFiles(x86)%\Steam\steamapps\common\SteamVR" - you can paste that into the Windows Run dialog and it should open the right folder. You can also find SteamVR in the Library, Tools section of Steam, right-click it, choose Properties, then Local Files, then "Browse local files..."

"The right folder" will contain, among other things, a directory called drivers.
Upon extracting the OSVR driver, you'll get a SteamVR-OSVR directory, with a drivers directory inside it (with additional directories and files deeper inside drivers).

You'll want to drag the drivers directory from the SteamVR-OSVR extracted folder over into the Steam directory, to merge its contents with the existing contents of the drivers directory. (It should just making an osvr subdirectory with contents.)
=  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  = 

~~ something i don't figure out now
"... you can paste that into the Windows Run dialog and it should open the right folder"
what the "the Windows Run dialog" and "the right folder" refer to ?

After reading the 3rd paragraph but not konwing it very well, i just copied the osvr folder (in "drivers" or the downloaded steamvr-osvr driver) to the drivers directory deep in steamvr install directory (now there are "lighhouse", "null", "oculus", "osvr" folders, and a file drivers.cfg in steamvr's drivers directory)

is this action is equivalent to what the 3rd paragraph mean?

**Comment by pavlo1031** [comment]
one thing i like to know is ~ "What do i have to do with this project?"

what i've done was just:
1). download the "Windows alpha binaries: Download Windows Alpha" suggested in the instruction.
2). copy its driver's stuff to steamVR's drivers direcotory.
3). launch osvr server & steamVR.

[!] Until now i havent' done anything with this project, such as copying this/part of the project to osvr install directory or sth like this.

~I've once guessed if i should rebuild it for my own driver and you said it's not.
Is there any i do with this project?

**Comment by pavlo1031** [comment]
i downgraded steamVR and it does not crash now; it still shows warning messagebox that says "VR_Init failed with Unable to initialize neccessory OpenVR interfaces."

Then i run Team Fortress 2. i can change screen direction by hovering the mouse right & left, but i don't know if the osvr HMD is really interacting with steam.

What does it look like when they interacts normally? rotating the hmd by an angle can change screen direction in the game? (for now it's not)

Could you please tell me how to ensure if steam and osvr hmd are interacting normally?

**Comment by Someguysname** [comment]
I'm also unable to get SteamVR working properly with my hmd. I'm using v1448479831 of SteamVR but I'm getting a timeout on the VR_Pipe instead. 
[vrclient_hellovr_sdl.txt](https://github.com/OSVR/SteamVR-OSVR/files/66061/vrclient_hellovr_sdl.txt)

**Comment by zhengjiezxxy** [comment]
@pavlo1031 how to downgrade steamvr? Steam will update the software automatically.

**Comment by d235j** [comment]
I'm having a hard time to get this to work with any current version. I'm sorry there isn't more progress, but it's not in my hands at this point.

**Comment by pavlo1031** [comment]
Finally...steam apps now are coworking with osvr hmd now!!
 1). Please upgrade/downgrade SteamVR to the version "v1444268063".
      [!] right-click on steamvr item, open the "properties" window, go to the "BETAS" tab
          you'll see a drop-down list, and select the version you wanna use, and re-downloading
         and re-installation will start then.

 2). Before you run steam app (hellovr_sdl.exe or other steam games), please confirm your pc's resolution is set to exactly 1920x1080.
      (if your computer does not support such a high resolution, your can use other monitor, like TV)

 3). Start SteamVR.

 4). Start the game.

 5). After entering the game (for example, Team Fortress 2), there is a button
    "Activate virtual Reality Mode" or sth like that, click on it, and the screen will become side-by-side.


 P.S. If still failed, set launch parameter "-vr" (do not include the double-quote) to the steam app
        or game that you're going to run.
        [!] Same way open the "properties" window, you may see something about launch parameter
            set it to -vr and start the game.

After i did these 3 steps, everything works fine, hope it helps :) !!

**Comment by typhoidcoma** [comment]
Just got the files to build on Win 10, no longer getting a crash with latest SteamVR beta and latest Core, but now Its back to not reconizing the HMD.  Progress :-)

**Comment by fatalnickle** [comment]
What core version Tyhpoid? Im pretty sure I have the latest.. SteamVR doesnt crash anymore, but still isnt detecting my osvr.

**Comment by zhengjiezxxy** [comment]
version "v1444268063" doesn't work for me(latest driver). The error is not recognizing the HDM. But v1448479831 works.

**Comment by fatalnickle** [comment]
Nice. Kind of half way working. Still says Not Ready, and my left and right's seem to be backwards. even though when i look at the screen under the lenses its not. I put it on and theyre backwards. its weird.  Keeps telling me Compositor is not fullscreen as well, when it is.

**Comment by fatalnickle** [comment]
![image](https://cloud.githubusercontent.com/assets/16602967/12190774/99e042c0-b59a-11e5-8dc5-67562e75306c.png)

**Comment by typhoidcoma** [comment]
Yup, looks pretty typical as of late.

**Comment by fatalnickle** [comment]
When I look at my screen under the lenses it looks just like that. But when I put it on I can see the left side in my right eye and the right side in my left eye... So confusing.

**Comment by zhengjiezxxy** [comment]
@pavlo1031  which versions of core and plugin do you use?

**Comment by typhoidcoma** [comment]
Downloaded v0.6-740-g0195020 and updated to the latest SteamVR beta on Win 10.  Works like a friggin charm.  Having some camera height calibration issues, but I think I can work through that with the config file. Also using latest core snapshot.

**Comment by zhengjiezxxy** [comment]
@typhoidcoma  Also using latest core snapshot. do you mean the latest plugin?

**Comment by typhoidcoma** [comment]
Yes latest plugin as well.
https://bintray.com/osvr/SteamVR-OSVR/SteamVR-OSVR-Win/v0.1-35-g8a0724b-core-v0.6-740-g0195020/view

**Comment by zhengjiezxxy** [comment]
@typhoidcoma Thanks. It work on me(windows7), I can run the demo(hellovr_sdl.exe ), but when I play Team Fortress 2, I cannot find "Virtual Reality" mode, and there is a message box that says " Init failed with unable to initialize necessary OpenVR interface.

**Comment by toxicFork** [comment]
Is your HMD / HDK display on portrait or landscape, and is it to the left
or right of your other displays, and what is its resolution? Can you take a
screenshot of your monitor arrangement window please? I think it may be
related to another issue.

**Comment by zhengjiezxxy** [comment]
This is my display settings.

![display1](https://cloud.githubusercontent.com/assets/5151510/12229964/832a3be0-b887-11e5-905d-802f39a00082.PNG)

![display2](https://cloud.githubusercontent.com/assets/5151510/12229971/9b2440d8-b887-11e5-9bcc-13f53ec7b6ad.PNG)

**Comment by toxicFork** [comment]
Hmm... I think it's because your main window is not 1920 pixels wide... Can
you try setting it to 1920 wide please? May be related to #23.

**Comment by fieldy1** [comment]
Ok all, u can get this working by doing the following - 
Steamvr = latest version
Osvr-steam driver = SteamVR-OSVR-Win-Build-v0.1-35-g8a0724b-core-v0.6-743-g790672e.7z 

This works for me and I can run hl2, I'm testing more this week

**Comment by godbyk** [comment]
We've just released an updated SteamVR-OSVR driver that should work with the current release of SteamVR. Please give it a try and report back if you encounter any problems.

**Comment by godbyk** [comment]
I'm closing this isssue due to a lack of information. If you are the original filer of this issue and still encounter this problem, feel free to reopen this issue. If you're not the original filer of this issue, please open a new issue instead.
